name: "Github Actions Weather Bot"

on:
    schedule:
        - '15 7 * * *'

jobs:
    bot:
        steps:
            - name: 'install node'
                uses: actions/setup-node@v1
            - name: 'install npm dependencies'
                run: npm install
            - name: 'Execute the code'
                 run: node index.js
            env: 
                TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
                TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                TELEGRAM_WEATHER_API: ${{ secrets.TELEGRAM_WEATHER_API }}