name: "Github Actions Weather Bot"

on:
    push:
    schedule:
            - cron: '15 7 * * *'

jobs:
    bot:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: 'Install node'
            uses: actions/setup-node@v1
        - name: 'Install NPM dependencies'
            run: npm install
        - name: 'Execute the code'
            run: node index.js
            env: 
                TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
                TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                TELEGRAM_WEATHER_API: ${{ secrets.TELEGRAM_WEATHER_API }}